# Generated by Django 6.0.3 on 2026-04-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=100)),
                ("difficulty", models.CharField(max_length=50)),
                ("topic", models.CharField(max_length=100)),
                ("scenario", models.TextField()),
                ("given_code", models.TextField()),
                ("expected_output", models.TextField()),
                ("constraints", models.JSONField(default=list)),
                ("solution", models.TextField()),
                ("evaluation_criteria", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
