# Generated by Django 6.0.3 on 2026-04-04 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="domain",
            field=models.CharField(db_index=True, default="general", max_length=100),
        ),
        migrations.AddField(
            model_name="task",
            name="generation_source",
            field=models.CharField(
                choices=[
                    ("vault", "Vault-based"),
                    ("ai_core", "AI-generated"),
                    ("fallback", "Static Fallback"),
                ],
                default="vault",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="generation_time_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="retries_used",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="GenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_number", models.IntegerField()),
                ("tier", models.CharField(max_length=20)),
                ("attempt_number", models.IntegerField()),
                ("was_duplicate", models.BooleanField(default=False)),
                ("was_invalid", models.BooleanField(default=False)),
                ("error_msg", models.TextField(blank=True, null=True)),
                ("source", models.CharField(max_length=20)),
                ("duration_ms", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.season"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
