# Generated by Django 5.0.3 on 2026-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_evaluation_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="hints",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="solution_approach",
            field=models.TextField(blank=True, null=True),
        ),
    ]
