# Generated by Django 5.0.3 on 2026-04-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_userprofile_gamesession_userlevelprogress"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="level",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="level",
            name="domain",
            field=models.CharField(db_index=True, default="dsa", max_length=100),
        ),
        migrations.AddField(
            model_name="task",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="hints",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(default="code_complete", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_accuracy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name="level",
            unique_together={("level_number", "season", "domain")},
        ),
        migrations.CreateModel(
            name="DailyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("domain", models.CharField(max_length=100)),
                ("reward_multiplier", models.FloatField(default=2.0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomainProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=100)),
                ("xp", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("accuracy", models.FloatField(default=0.0)),
                ("completed_levels", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_progress",
                        to="tasks.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "domain")},
            },
        ),
    ]
