# Generated by Django 5.0.3 on 2026-04-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_level_unique_together_level_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="selected_domain",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
