# Generated by Django 5.0.3 on 2026-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_userprofile_selected_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="solution",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streak_multiplier",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_correct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_submissions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="domain",
            field=models.CharField(db_index=True, default="dsa", max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("bug_fix", "Bug Fix"),
                    ("code_complete", "Code Complete"),
                    ("output_prediction", "Output Prediction"),
                    ("optimization", "Optimization"),
                ],
                default="code_complete",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="coins",
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="lives",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="selected_domain",
            field=models.CharField(default="dsa", max_length=50),
        ),
    ]
