# Generated by Django 5.0.3 on 2026-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_dailychallenge_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="recent_task_cache",
            field=models.TextField(
                default="[]", help_text="JSON list of last 50 task hashes for this user"
            ),
        ),
    ]
